#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Car_Renting_System
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Car Renting")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAccount(Account instance);
    partial void UpdateAccount(Account instance);
    partial void DeleteAccount(Account instance);
    partial void InsertXe(Xe instance);
    partial void UpdateXe(Xe instance);
    partial void DeleteXe(Xe instance);
    partial void InsertThue(Thue instance);
    partial void UpdateThue(Thue instance);
    partial void DeleteThue(Thue instance);
    partial void InserttempThue(tempThue instance);
    partial void UpdatetempThue(tempThue instance);
    partial void DeletetempThue(tempThue instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::Car_Renting_System.Properties.Settings.Default.Car_RentingConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Account> Accounts
		{
			get
			{
				return this.GetTable<Account>();
			}
		}
		
		public System.Data.Linq.Table<Xe> Xes
		{
			get
			{
				return this.GetTable<Xe>();
			}
		}
		
		public System.Data.Linq.Table<Thue> Thues
		{
			get
			{
				return this.GetTable<Thue>();
			}
		}
		
		public System.Data.Linq.Table<tempThue> tempThues
		{
			get
			{
				return this.GetTable<tempThue>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Account")]
	public partial class Account : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _UserName;
		
		private string _Password;
		
		private string _Email;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    #endregion
		
		public Account()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(30)")]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(30)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(30)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Xe")]
	public partial class Xe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Bien_So;
		
		private string _Ten_Xe;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnBien_SoChanging(string value);
    partial void OnBien_SoChanged();
    partial void OnTen_XeChanging(string value);
    partial void OnTen_XeChanged();
    #endregion
		
		public Xe()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bien_So", DbType="NVarChar(30)")]
		public string Bien_So
		{
			get
			{
				return this._Bien_So;
			}
			set
			{
				if ((this._Bien_So != value))
				{
					this.OnBien_SoChanging(value);
					this.SendPropertyChanging();
					this._Bien_So = value;
					this.SendPropertyChanged("Bien_So");
					this.OnBien_SoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten_Xe", DbType="NVarChar(30)")]
		public string Ten_Xe
		{
			get
			{
				return this._Ten_Xe;
			}
			set
			{
				if ((this._Ten_Xe != value))
				{
					this.OnTen_XeChanging(value);
					this.SendPropertyChanging();
					this._Ten_Xe = value;
					this.SendPropertyChanged("Ten_Xe");
					this.OnTen_XeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Thue")]
	public partial class Thue : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Ten_KH;
		
		private string _CCCD;
		
		private System.Nullable<int> _Thoi_Gian;
		
		private string _Phan_Loai;
		
		private string _Chon_Xe;
		
		private System.Nullable<System.DateTime> _Tu_Ngay;
		
		private System.Nullable<int> _Thanh_Tien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnTen_KHChanging(string value);
    partial void OnTen_KHChanged();
    partial void OnCCCDChanging(string value);
    partial void OnCCCDChanged();
    partial void OnThoi_GianChanging(System.Nullable<int> value);
    partial void OnThoi_GianChanged();
    partial void OnPhan_LoaiChanging(string value);
    partial void OnPhan_LoaiChanged();
    partial void OnChon_XeChanging(string value);
    partial void OnChon_XeChanged();
    partial void OnTu_NgayChanging(System.Nullable<System.DateTime> value);
    partial void OnTu_NgayChanged();
    partial void OnThanh_TienChanging(System.Nullable<int> value);
    partial void OnThanh_TienChanged();
    #endregion
		
		public Thue()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten_KH", DbType="NVarChar(30)")]
		public string Ten_KH
		{
			get
			{
				return this._Ten_KH;
			}
			set
			{
				if ((this._Ten_KH != value))
				{
					this.OnTen_KHChanging(value);
					this.SendPropertyChanging();
					this._Ten_KH = value;
					this.SendPropertyChanged("Ten_KH");
					this.OnTen_KHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CCCD", DbType="NVarChar(30)")]
		public string CCCD
		{
			get
			{
				return this._CCCD;
			}
			set
			{
				if ((this._CCCD != value))
				{
					this.OnCCCDChanging(value);
					this.SendPropertyChanging();
					this._CCCD = value;
					this.SendPropertyChanged("CCCD");
					this.OnCCCDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thoi_Gian", DbType="Int")]
		public System.Nullable<int> Thoi_Gian
		{
			get
			{
				return this._Thoi_Gian;
			}
			set
			{
				if ((this._Thoi_Gian != value))
				{
					this.OnThoi_GianChanging(value);
					this.SendPropertyChanging();
					this._Thoi_Gian = value;
					this.SendPropertyChanged("Thoi_Gian");
					this.OnThoi_GianChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phan_Loai", DbType="NVarChar(30)")]
		public string Phan_Loai
		{
			get
			{
				return this._Phan_Loai;
			}
			set
			{
				if ((this._Phan_Loai != value))
				{
					this.OnPhan_LoaiChanging(value);
					this.SendPropertyChanging();
					this._Phan_Loai = value;
					this.SendPropertyChanged("Phan_Loai");
					this.OnPhan_LoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Chon_Xe", DbType="NVarChar(30)")]
		public string Chon_Xe
		{
			get
			{
				return this._Chon_Xe;
			}
			set
			{
				if ((this._Chon_Xe != value))
				{
					this.OnChon_XeChanging(value);
					this.SendPropertyChanging();
					this._Chon_Xe = value;
					this.SendPropertyChanged("Chon_Xe");
					this.OnChon_XeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tu_Ngay", DbType="DateTime")]
		public System.Nullable<System.DateTime> Tu_Ngay
		{
			get
			{
				return this._Tu_Ngay;
			}
			set
			{
				if ((this._Tu_Ngay != value))
				{
					this.OnTu_NgayChanging(value);
					this.SendPropertyChanging();
					this._Tu_Ngay = value;
					this.SendPropertyChanged("Tu_Ngay");
					this.OnTu_NgayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thanh_Tien", DbType="Int")]
		public System.Nullable<int> Thanh_Tien
		{
			get
			{
				return this._Thanh_Tien;
			}
			set
			{
				if ((this._Thanh_Tien != value))
				{
					this.OnThanh_TienChanging(value);
					this.SendPropertyChanging();
					this._Thanh_Tien = value;
					this.SendPropertyChanged("Thanh_Tien");
					this.OnThanh_TienChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tempThue")]
	public partial class tempThue : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Ten_KH;
		
		private string _CCCD;
		
		private System.Nullable<int> _Thoi_Gian;
		
		private string _Phan_Loai;
		
		private string _Chon_Xe;
		
		private System.Nullable<System.DateTime> _Tu_Ngay;
		
		private System.Nullable<int> _Thanh_Tien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnTen_KHChanging(string value);
    partial void OnTen_KHChanged();
    partial void OnCCCDChanging(string value);
    partial void OnCCCDChanged();
    partial void OnThoi_GianChanging(System.Nullable<int> value);
    partial void OnThoi_GianChanged();
    partial void OnPhan_LoaiChanging(string value);
    partial void OnPhan_LoaiChanged();
    partial void OnChon_XeChanging(string value);
    partial void OnChon_XeChanged();
    partial void OnTu_NgayChanging(System.Nullable<System.DateTime> value);
    partial void OnTu_NgayChanged();
    partial void OnThanh_TienChanging(System.Nullable<int> value);
    partial void OnThanh_TienChanged();
    #endregion
		
		public tempThue()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten_KH", DbType="NVarChar(30)")]
		public string Ten_KH
		{
			get
			{
				return this._Ten_KH;
			}
			set
			{
				if ((this._Ten_KH != value))
				{
					this.OnTen_KHChanging(value);
					this.SendPropertyChanging();
					this._Ten_KH = value;
					this.SendPropertyChanged("Ten_KH");
					this.OnTen_KHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CCCD", DbType="NVarChar(50)")]
		public string CCCD
		{
			get
			{
				return this._CCCD;
			}
			set
			{
				if ((this._CCCD != value))
				{
					this.OnCCCDChanging(value);
					this.SendPropertyChanging();
					this._CCCD = value;
					this.SendPropertyChanged("CCCD");
					this.OnCCCDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thoi_Gian", DbType="Int")]
		public System.Nullable<int> Thoi_Gian
		{
			get
			{
				return this._Thoi_Gian;
			}
			set
			{
				if ((this._Thoi_Gian != value))
				{
					this.OnThoi_GianChanging(value);
					this.SendPropertyChanging();
					this._Thoi_Gian = value;
					this.SendPropertyChanged("Thoi_Gian");
					this.OnThoi_GianChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phan_Loai", DbType="NVarChar(30)")]
		public string Phan_Loai
		{
			get
			{
				return this._Phan_Loai;
			}
			set
			{
				if ((this._Phan_Loai != value))
				{
					this.OnPhan_LoaiChanging(value);
					this.SendPropertyChanging();
					this._Phan_Loai = value;
					this.SendPropertyChanged("Phan_Loai");
					this.OnPhan_LoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Chon_Xe", DbType="NVarChar(30)")]
		public string Chon_Xe
		{
			get
			{
				return this._Chon_Xe;
			}
			set
			{
				if ((this._Chon_Xe != value))
				{
					this.OnChon_XeChanging(value);
					this.SendPropertyChanging();
					this._Chon_Xe = value;
					this.SendPropertyChanged("Chon_Xe");
					this.OnChon_XeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tu_Ngay", DbType="DateTime")]
		public System.Nullable<System.DateTime> Tu_Ngay
		{
			get
			{
				return this._Tu_Ngay;
			}
			set
			{
				if ((this._Tu_Ngay != value))
				{
					this.OnTu_NgayChanging(value);
					this.SendPropertyChanging();
					this._Tu_Ngay = value;
					this.SendPropertyChanged("Tu_Ngay");
					this.OnTu_NgayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thanh_Tien", DbType="Int")]
		public System.Nullable<int> Thanh_Tien
		{
			get
			{
				return this._Thanh_Tien;
			}
			set
			{
				if ((this._Thanh_Tien != value))
				{
					this.OnThanh_TienChanging(value);
					this.SendPropertyChanging();
					this._Thanh_Tien = value;
					this.SendPropertyChanged("Thanh_Tien");
					this.OnThanh_TienChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
